FROM kraft-lab-base:latest

COPY config/zoo.cfg /opt/kafka/config/zoo.cfg
COPY config/zookeeper.service /etc/systemd/system/zookeeper.service
COPY config/java.env /opt/kafka/config/java.env

RUN mkdir -p /zookeeper/data /zookeeper/log

CMD [ "/sbin/init" ]
